export const GEt_BURGER_INGRIDIENTS__REQUEST = 'GEt_BURGER_INGRIDIENTS__REQUEST'
export const GEt_BURGER_INGRIDIENTS_SUCCESS = 'GEt_BURGER_INGRIDIENTS_SUCCESS'
export const GEt_BURGER_INGRIDIENTS_ERROR = 'GEt_BURGER_INGRIDIENTS_ERROR'
export const GET_BURGER_CONSTRUCTOR = 'GET_BURGER_CONSTRUCTOR'
export const GET_ON_MODAL_INGRIDIENTS = 'GET_ON_MODAL_INGRIDIENTS'
export const DELETE_MODAL_INGRIDIENTS = 'DELETE_MODAL_INGRIDIENTS'
export const GET_ORDER_NUMBER_REQUEST = 'GET_ORDER_NUMBER__REQUEST'
export const GET_ORDER_NUMBER_SUCCESS = 'GET_ORDER_NUMBER_SUCCESS'
export const GET_ORDER_NUMBER_ERROR = 'GET_ORDER_NUMBER_ERROR'
export const HIDE_ORDER_MODAL = 'HIDE_ORDER_MODAL'
export const UPDATE_CONSTRUCTOR_LIST = 'UPDATE_CONSTRUCTOR_LIST'
export const RELOAD_CONSTRUCTOR_LIST = 'RELOAD_CONSTRUCTOR_LIST'
export const DELETE_CONSTRUCTOR_ELEMENT = 'DELETE_CONSTRUCTOR_ELEMENT'
export const UPDATE_BUN = 'UPDATE_BUN'

//user
export const SET_USER_REQUEST = 'SET_USER_REQUEST'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'

//refresh

export const REFRESH_REQUEST = 'REFRESH_REQUEST'
export const REFRESH_ERROR = 'REFRESH_ERROR'
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const PASS_REFRESH_REQUEST = 'PASS_REFRESH_REQUEST'
export const PASS_REFRESH_ERROR = 'PASS_REFRESH_ERROR'
export const PASS_REFRESH_SUCCESS = 'PASS_REFRESH_SUCCESS'

//websocket

export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';

export const wsActions = {
    wsInit: WS_CONNECTION_START,
    wsSendMessage: WS_SEND_MESSAGE,
    onOpen: WS_CONNECTION_SUCCESS,
    onClose: WS_CONNECTION_CLOSED,
    onError: WS_CONNECTION_ERROR,
    onMessage: WS_GET_MESSAGE
  };
  